### ISSUE TITLE
About the environment requirement

### ISSUE THREAD

**Issue by YaNjIeE** [ChuanMeng/DukeNet#1]
Hi, thanks for the open source of Dukenet. 

I try to run this code but got **segmentation fault (core dumped)**. It seems that the dependency of some python libs (maybe pytorch/transformers/cudatoolkit/cudnn version) is not compatible with the code.

I wonder if you can provide the specific versions of the python libs needed for the code.

I appreciate for that a lot.

Best.

**Comment by YaNjIeE** [comment]
Solved. 
Thanks.

**Comment by ChuanMeng** [comment]
Hi, the Cuda version of this code is 10.0.
